/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 注册（自动创建个人组织 + 默认项目 + dev/staging/prod） */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登录（限流 5 次/分钟/IP）；已开 2FA 返回 totp_required + challenge */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 刷新 token（旋转：旧 refresh 立即失效） */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/totp/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 生成 TOTP 待激活密钥（返回 secret / otpauth URL / 二维码 PNG） */
        post: operations["totpSetup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/totp/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 校验动态码并激活 2FA（签发 10 个恢复码，仅展示一次） */
        post: operations["totpVerify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/totp/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 关闭 2FA（需密码确认，恢复码一并作废） */
        post: operations["totpDisable"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/totp/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 2FA 第二步：challenge + 动态码/恢复码 → 换正式 token（限流） */
        post: operations["totpLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前用户 + 组织列表 + 2FA 状态 */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{slug}/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 组织项目列表 */
        get: operations["listProjects"];
        put?: never;
        /** 新建项目（自动建 dev/staging/prod + 根文件夹） */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{slug}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 审计日志（append-only） */
        get: operations["audit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{slug}/identities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 机器身份列表（owner/admin） */
        get: operations["listIdentities"];
        put?: never;
        /** 创建机器身份（client_secret 仅此一次返回） */
        post: operations["createIdentity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{slug}/identities/{id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 吊销机器身份（token 立即失效） */
        post: operations["revokeIdentity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identities/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** client_credentials 换短期 JWT（限流） */
        post: operations["identityToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{pid}/environments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 项目环境列表 */
        get: operations["listEnvs"];
        put?: never;
        /** 新建环境（自动建根文件夹） */
        post: operations["createEnv"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{pid}/folders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 平铺文件夹列表（前端按 parent_id 建树） */
        get: operations["listFolders"];
        put?: never;
        /** 创建文件夹（自动补中间节点，幂等） */
        post: operations["createFolder"];
        /** 删除空文件夹（无子目录且无密钥；根目录拒绝） */
        delete: operations["deleteFolder"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{pid}/folders/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 移动/重命名文件夹（级联更新子孙物化路径与密钥 folder 冗余列） */
        post: operations["moveFolder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{pid}/secrets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 密钥列表（无值；?path= 按文件夹过滤，缺省全环境） */
        get: operations["listSecrets"];
        put?: never;
        /** 创建/更新密钥（AES-256-GCM 信封加密，产生新版本；同 key 不同目录互不冲突） */
        post: operations["upsertSecret"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{pid}/secrets/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取明文（reveal 权限，记审计；?path= 定位目录） */
        get: operations["revealSecret"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{pid}/secrets/{key}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 版本历史（只追加） */
        get: operations["secretVersions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{pid}/secrets/{key}/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 回滚到历史版本（以旧值产生新版本 v+1） */
        post: operations["rollbackSecret"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{pid}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 导出 .env 格式（reveal 权限；值仅出现在响应体） */
        get: operations["exportSecrets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @example BAD_CREDENTIALS */
            code?: string;
            message?: string;
            details?: {
                [key: string]: unknown;
            };
        };
        User: {
            id?: string;
            /** Format: email */
            email?: string;
            name?: string;
        };
        OrgMembership: {
            id?: string;
            name?: string;
            slug?: string;
            /** @enum {string} */
            role?: "owner" | "admin" | "developer" | "viewer";
        };
        Project: {
            id?: string;
            name?: string;
            slug?: string;
            /** Format: date-time */
            created_at?: string;
        };
        Environment: {
            id?: string;
            name?: string;
            slug?: string;
            sort_order?: number;
        };
        Folder: {
            id?: string;
            /** @description 根目录为空串 */
            parent_id?: string;
            name?: string;
            /** @example /db/mysql/ */
            path?: string;
        };
        SecretMeta: {
            id?: string;
            folder?: string;
            key?: string;
            comment?: string;
            tags?: string[];
            version?: number;
            updated_at?: string;
            canReveal?: boolean;
        };
        SecretValue: components["schemas"]["SecretMeta"] & {
            value?: string;
        };
        SecretVersion: {
            version?: number;
            created_by?: string;
            created_at?: string;
        };
        SecretUpsertRequest: {
            key: string;
            value: string;
            comment?: string;
            tags?: string[];
        };
        AuditLog: {
            id?: string;
            actor_name?: string;
            /** @example secrets.reveal */
            action?: string;
            resource?: string;
            metadata?: string;
            ip?: string;
            created_at?: string;
        };
        IdentityScope: {
            project_id?: string;
            project_slug?: string;
            /** @description 显式环境，禁止通配 */
            env?: string;
            /** @enum {string} */
            permission?: "read" | "write";
        };
        Identity: {
            id?: string;
            name?: string;
            client_id?: string;
            /** @enum {string} */
            status?: "active" | "revoked";
            token_ttl?: number;
            created_at?: string;
            scopes?: components["schemas"]["IdentityScope"][];
        };
        IdentityWithSecret: components["schemas"]["Identity"] & {
            /** @description 仅此一次展示 */
            client_secret?: string;
        };
        IdentityCreateRequest: {
            name: string;
            /** @default 900 */
            token_ttl: number;
            scopes: {
                project_id: string;
                env: string;
                /** @enum {string} */
                permission: "read" | "write";
            }[];
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
            name?: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        TokenPair: {
            access?: string;
            refresh?: string;
            /** @example Bearer */
            tokenType?: string;
            /** @example 900 */
            expiresIn?: number;
        };
        AuthResponse: {
            user?: components["schemas"]["User"];
            tokens?: components["schemas"]["TokenPair"];
        };
        LoginResponse: components["schemas"]["AuthResponse"] | {
            /** @constant */
            totp_required?: true;
            challenge?: string;
        };
    };
    responses: {
        /** @description 参数错误 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 未认证/凭证错误 */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 权限不足（RBAC），如 viewer 取明文、developer 写 prod */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 资源不存在 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 冲突（如邮箱已注册） */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 限流（5 次/分钟/IP，可用 TABOO_LOGIN_RATE_LIMIT 调整） */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        OrgSlug: string;
        Pid: string;
        Env: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description 注册成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description 登录成功（或需二次验证） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    refresh: string;
                };
            };
        };
        responses: {
            /** @description 新 token 对 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    totpSetup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 待激活密钥（secret 明文仅此一次展示） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example JBSWY3DPEHPK3PXP */
                        secret?: string;
                        /** Format: uri */
                        otpauth_url?: string;
                        /** @description data:image/png;base64 */
                        qr_png?: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    totpVerify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example 123456 */
                    code: string;
                };
            };
        };
        responses: {
            /** @description 已开启 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        enabled?: boolean;
                        recovery_codes?: string[];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    totpDisable: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: password */
                    password: string;
                };
            };
        };
        responses: {
            /** @description 已关闭 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example false */
                        enabled?: boolean;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    totpLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description login 返回的 5min JWT */
                    challenge: string;
                    /** @description 6 位动态码或 xxxx-xxx-xxxx 恢复码 */
                    code: string;
                };
            };
        };
        responses: {
            /** @description 登录成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前用户 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user?: components["schemas"]["User"];
                        orgs?: components["schemas"]["OrgMembership"][];
                        totp_enabled?: boolean;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["OrgSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 项目列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        projects?: components["schemas"]["Project"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["OrgSlug"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                };
            };
        };
        responses: {
            /** @description 已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    audit: {
        parameters: {
            query?: {
                limit?: number;
                /** @description cursor 分页预留（当前按时间倒序 limit） */
                before?: string;
            };
            header?: never;
            path: {
                slug: components["parameters"]["OrgSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 审计记录 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        logs?: components["schemas"]["AuditLog"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listIdentities: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["OrgSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 身份列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        identities?: components["schemas"]["Identity"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createIdentity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["OrgSlug"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IdentityCreateRequest"];
            };
        };
        responses: {
            /** @description 已创建（含一次性 client_secret） */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentityWithSecret"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    revokeIdentity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["OrgSlug"];
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已吊销 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    identityToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    client_id: string;
                    client_secret: string;
                };
            };
        };
        responses: {
            /** @description 短期 token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        access_token?: string;
                        /** @example Bearer */
                        token_type?: string;
                        /** @example 900 */
                        expires_in?: number;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
        };
    };
    listEnvs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: components["parameters"]["Pid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 环境列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        environments?: components["schemas"]["Environment"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createEnv: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: components["parameters"]["Pid"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                };
            };
        };
        responses: {
            /** @description 已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Environment"];
                };
            };
        };
    };
    listFolders: {
        parameters: {
            query?: {
                env?: components["parameters"]["Env"];
            };
            header?: never;
            path: {
                pid: components["parameters"]["Pid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 文件夹列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        folders?: components["schemas"]["Folder"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createFolder: {
        parameters: {
            query?: {
                env?: components["parameters"]["Env"];
            };
            header?: never;
            path: {
                pid: components["parameters"]["Pid"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example /db/mysql/ */
                    path: string;
                };
            };
        };
        responses: {
            /** @description 已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id?: string;
                        path?: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    deleteFolder: {
        parameters: {
            query: {
                env?: components["parameters"]["Env"];
                path: string;
            };
            header?: never;
            path: {
                pid: components["parameters"]["Pid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已删除 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    moveFolder: {
        parameters: {
            query?: {
                env?: components["parameters"]["Env"];
            };
            header?: never;
            path: {
                pid: components["parameters"]["Pid"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example /db/ */
                    from: string;
                    /** @example /database/ */
                    to: string;
                };
            };
        };
        responses: {
            /** @description 已移动 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    listSecrets: {
        parameters: {
            query?: {
                env?: components["parameters"]["Env"];
                path?: string;
            };
            header?: never;
            path: {
                pid: components["parameters"]["Pid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 密钥元数据列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        secrets?: components["schemas"]["SecretMeta"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    upsertSecret: {
        parameters: {
            query?: {
                env?: components["parameters"]["Env"];
                path?: string;
            };
            header?: {
                /** @description 幂等约定（v1.5 强制） */
                "Idempotency-Key"?: string;
            };
            path: {
                pid: components["parameters"]["Pid"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SecretUpsertRequest"];
            };
        };
        responses: {
            /** @description 已保存（含新版本号） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        version?: number;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
        };
    };
    revealSecret: {
        parameters: {
            query?: {
                env?: components["parameters"]["Env"];
                path?: string;
            };
            header?: never;
            path: {
                pid: components["parameters"]["Pid"];
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 明文 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecretValue"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    secretVersions: {
        parameters: {
            query?: {
                env?: components["parameters"]["Env"];
                path?: string;
            };
            header?: never;
            path: {
                pid: components["parameters"]["Pid"];
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 版本列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        versions?: components["schemas"]["SecretVersion"][];
                        latest?: number;
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    rollbackSecret: {
        parameters: {
            query?: {
                env?: components["parameters"]["Env"];
                path?: string;
            };
            header?: never;
            path: {
                pid: components["parameters"]["Pid"];
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    version: number;
                };
            };
        };
        responses: {
            /** @description 已回滚 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        version?: number;
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    exportSecrets: {
        parameters: {
            query?: {
                env?: components["parameters"]["Env"];
            };
            header?: never;
            path: {
                pid: components["parameters"]["Pid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description text/plain .env 内容 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": unknown;
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
}
