/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 进程存活 */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 就绪（SELECT 1 + schema 版本） */
        get: operations["readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 登录页 Realm 列表（仅 public_login 的 IdP）以及本地注册/密码是否开放 */
        get: operations["listAuthSources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 注册（自动创建个人组织 + 默认项目 + dev/staging/prod） */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登录（限流 5 次/分钟/IP）；已开 2FA 返回 totp_required + challenge */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 刷新 token（旋转：旧 refresh 立即失效） */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/totp/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 生成 TOTP 待激活密钥（返回 secret / otpauth URL / 二维码 PNG） */
        post: operations["totpSetup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/totp/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 校验动态码并激活 2FA（签发 10 个恢复码，仅展示一次） */
        post: operations["totpVerify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/totp/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 关闭 2FA（需密码确认，恢复码一并作废） */
        post: operations["totpDisable"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/totp/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 2FA 第二步：challenge + 动态码/恢复码 → 换正式 token（限流） */
        post: operations["totpLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前用户 + 组织列表 + 2FA 状态 */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{slug}/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 组织项目列表 */
        get: operations["listProjects"];
        put?: never;
        /** 新建项目（自动建 dev/staging/prod + 根文件夹） */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{slug}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 审计日志（append-only） */
        get: operations["audit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{slug}/audit/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 验真审计哈希链与 checkpoint */
        get: operations["verifyAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{slug}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 成员列表（owner） */
        get: operations["listMembers"];
        put?: never;
        /** 添加已注册用户为成员 */
        post: operations["addMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{slug}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 移除成员 */
        delete: operations["removeMember"];
        options?: never;
        head?: never;
        /** 改角色 / restricted */
        patch: operations["patchMember"];
        trace?: never;
    };
    "/api/v1/orgs/{slug}/members/{userId}/grants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 替换项目授权矩阵 */
        put: operations["putMemberGrants"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{slug}/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 创建邀请（自托管返回一次性链接） */
        post: operations["createInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invites/{token}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 接受邀请（登录用户邮箱须匹配） */
        post: operations["acceptInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{slug}/identities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 机器身份列表（owner/admin） */
        get: operations["listIdentities"];
        put?: never;
        /** 创建机器身份（client_secret 仅此一次返回） */
        post: operations["createIdentity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{slug}/identities/{id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 吊销机器身份（token 立即失效） */
        post: operations["revokeIdentity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identities/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** client_credentials 换短期 JWT（限流） */
        post: operations["identityToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{pid}/environments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 项目环境列表 */
        get: operations["listEnvs"];
        put?: never;
        /** 新建环境（自动建根文件夹） */
        post: operations["createEnv"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{pid}/folders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 平铺文件夹列表（前端按 parent_id 建树） */
        get: operations["listFolders"];
        put?: never;
        /** 创建文件夹（自动补中间节点，幂等） */
        post: operations["createFolder"];
        /** 删除空文件夹（无子目录且无密钥；根目录拒绝） */
        delete: operations["deleteFolder"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{pid}/folders/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 移动/重命名文件夹（级联更新子孙物化路径与密钥 folder 冗余列） */
        post: operations["moveFolder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{pid}/secrets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 密钥列表（无值；?path= 按文件夹过滤，缺省全环境） */
        get: operations["listSecrets"];
        put?: never;
        /** 创建/更新密钥（AES-256-GCM 信封加密，产生新版本；同 key 不同目录互不冲突） */
        post: operations["upsertSecret"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{pid}/secrets/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取明文（reveal 权限，记审计；?path= 定位目录） */
        get: operations["revealSecret"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{pid}/secrets/{key}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 版本历史（只追加） */
        get: operations["secretVersions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{pid}/secrets/{key}/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 回滚到历史版本（以旧值产生新版本 v+1） */
        post: operations["rollbackSecret"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{pid}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 导出 .env 格式（reveal 权限；值仅出现在响应体） */
        get: operations["exportSecrets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{pid}/dynamic-engines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 动态密钥引擎列表 + 活跃 lease（不含连接串/密码） */
        get: operations["listDynamicEngines"];
        put?: never;
        /** 创建 PostgreSQL 动态密钥引擎（owner/admin；连接串 Master Key 加密落库） */
        post: operations["createDynamicEngine"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{pid}/dynamic-engines/{eid}/lease": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 申请动态密钥 lease（仅限机器身份 token，绑定 identity；服务端 CREATE USER ... VALID UNTIL） */
        post: operations["requestLease"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{pid}/dynamic-leases/{lid}/renew": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 续期 lease（延长 VALID UNTIL，不超 max_ttl；lease 所属身份或 owner/admin） */
        post: operations["renewLease"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{pid}/dynamic-leases/{lid}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 手动回收 lease（立即 DROP USER；lease 所属身份或 owner/admin） */
        post: operations["revokeLease"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{slug}/sync/targets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 同步目标列表（成员可见；config 只回显已配置的键名） */
        get: operations["listSyncTargets"];
        put?: never;
        /** 创建同步目标（owner；平台凭证 Master Key 加密落库；?ping=1 先自检连通性） */
        post: operations["createSyncTarget"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{slug}/sync/targets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除同步目标（owner） */
        delete: operations["deleteSyncTarget"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{slug}/sync/targets/{id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 手动全量重推（owner；绑定范围内所有密钥入队） */
        post: operations["retrySyncTarget"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{slug}/sync/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 同步记录（指纹审计，不含明文；可按目标/状态筛选） */
        get: operations["listSyncRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{slug}/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Webhook 订阅列表（不含签名密钥） */
        get: operations["listWebhooks"];
        put?: never;
        /** 创建订阅（owner；secret 缺省自动生成，仅本次响应返回） */
        post: operations["createWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{slug}/webhooks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除订阅（owner） */
        delete: operations["deleteWebhook"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{slug}/webhooks/{id}/deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 投递日志（至少一次 + 指数退避；payload 不含明文） */
        get: operations["listWebhookDeliveries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/oidc/{slug}/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OIDC 登录入口（302 跳转 IdP；PKCE S256 + nonce；公开，限流保护） */
        get: operations["oidcLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/oidc/{slug}/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OIDC callback（code 换 id_token，验签 + JIT 入组 + 发本地会话） */
        get: operations["oidcCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{slug}/oidc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** IdP 配置列表（成员可见；不含 client_secret） */
        get: operations["listOIDCProviders"];
        put?: never;
        /** 接入 IdP（owner；创建前做 discovery 连通性自检；client_secret 加密落库） */
        post: operations["createOIDCProvider"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{slug}/oidc/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除 IdP 配置（owner） */
        delete: operations["deleteOIDCProvider"];
        options?: never;
        head?: never;
        /** 更新 IdP 配置（owner；client_secret 可选轮换） */
        patch: operations["updateOIDCProvider"];
        trace?: never;
    };
    "/api/v1/orgs/{slug}/audit/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 审计导出 CSV/JSONL（筛选同审计查询；async=1 走异步任务 + 下载链接） */
        get: operations["auditExport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{slug}/audit/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 导出任务列表 */
        get: operations["listAuditExports"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{slug}/audit/exports/{id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 失败的导出任务重试一次 */
        post: operations["retryAuditExport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{slug}/audit/exports/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 下载导出文件（未完成时返回任务状态） */
        get: operations["downloadAuditExport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @example BAD_CREDENTIALS */
            code?: string;
            message?: string;
            details?: {
                [key: string]: unknown;
            };
        };
        User: {
            id?: string;
            /** Format: email */
            email?: string;
            name?: string;
            /** @enum {string} */
            kind?: "user" | "identity";
        };
        AuthSource: {
            id?: string;
            name?: string;
            login_url?: string;
        };
        OrgMembership: {
            id?: string;
            name?: string;
            slug?: string;
            /** @enum {string} */
            role?: "owner" | "admin" | "developer" | "viewer";
            restricted?: boolean;
        };
        OrgMember: {
            user_id?: string;
            email?: string;
            name?: string;
            /** @enum {string} */
            role?: "owner" | "admin" | "developer" | "viewer";
            restricted?: boolean;
            joined_at?: string;
            grants?: {
                project_id?: string;
                project_slug?: string;
                project_name?: string;
                role?: string;
            }[];
        };
        Project: {
            id?: string;
            name?: string;
            slug?: string;
            /** Format: date-time */
            created_at?: string;
        };
        Environment: {
            id?: string;
            name?: string;
            slug?: string;
            sort_order?: number;
            protected?: boolean;
        };
        Folder: {
            id?: string;
            /** @description 根目录为空串 */
            parent_id?: string;
            name?: string;
            /** @example /db/mysql/ */
            path?: string;
        };
        SecretMeta: {
            id?: string;
            folder?: string;
            key?: string;
            comment?: string;
            tags?: string[];
            version?: number;
            updated_at?: string;
            canReveal?: boolean;
            canWrite?: boolean;
        };
        SecretValue: components["schemas"]["SecretMeta"] & {
            value?: string;
        };
        SecretVersion: {
            version?: number;
            created_by?: string;
            created_at?: string;
        };
        SecretUpsertRequest: {
            /** @description 单段 key，禁止包含 /（folder 与 key 分离，#16） */
            key: string;
            value: string;
            comment?: string;
            tags?: string[];
        };
        AuditLog: {
            id?: string;
            actor_name?: string;
            /** @example secrets.reveal */
            action?: string;
            resource?: string;
            metadata?: string;
            ip?: string;
            created_at?: string;
        };
        SyncTarget: {
            id?: string;
            name?: string;
            /** @enum {string} */
            platform?: "github" | "vercel" | "cloudflare";
            project_id?: string;
            /** @description '*' 为全部环境 */
            env_slug?: string;
            enabled?: boolean;
            created_at?: string;
            /** @description 已配置键名（不含值） */
            config_keys?: string[];
        };
        SyncTargetInput: {
            name: string;
            /** @enum {string} */
            platform: "github" | "vercel" | "cloudflare";
            /** @description 缺省 = 组织内全部项目 */
            project_id?: string;
            /** @default * */
            env_slug: string;
            /**
             * @description github: token/owner/repo/environment?(repo 级留空)；
             *     vercel: token/project_id/team_id?/targets?(逗号分隔，默认 production)；
             *     cloudflare: token/account_id/script_name
             */
            config: {
                [key: string]: string;
            };
        };
        SyncRun: {
            id?: string;
            target_id?: string;
            secret_key?: string;
            action?: string;
            /** @description 推送内容 sha256 前 16 hex（不含明文） */
            fingerprint?: string;
            /** @enum {string} */
            status?: "pending" | "success" | "failed" | "dead";
            /** @enum {string} */
            trigger_type?: "event" | "manual";
            attempts?: number;
            error?: string;
            created_at?: string;
            updated_at?: string;
        };
        Webhook: {
            id?: string;
            url?: string;
            /** @description 仅创建响应返回一次 */
            secret?: string;
            events?: string[];
            active?: boolean;
            created_at?: string;
        };
        OIDCProvider: {
            id?: string;
            name?: string;
            issuer?: string;
            client_id?: string;
            scopes?: string;
            role_claim?: string;
            username_claim?: string;
            role_map?: {
                [key: string]: string;
            };
            /** @enum {string} */
            default_role?: "viewer" | "developer" | "admin" | "owner";
            /** @description 在登录页展示为实例级 Realm */
            public_login?: boolean;
            autocreate?: boolean;
            /** @description 每次 SSO 登录按组映射同步角色（不降级最后一名 owner） */
            sync_role?: boolean;
            enabled?: boolean;
            created_at?: string;
            login_url?: string;
        };
        OIDCProviderInput: {
            name?: string;
            /** @example https://keycloak.example.com/realms/company */
            issuer?: string;
            client_id?: string;
            /** @description Master Key 加密落库，不回显；PATCH 时可省略 */
            client_secret?: string;
            /** @default openid */
            scopes: string;
            /**
             * @description 支持点分路径，如 realm_access.roles
             * @default groups
             */
            role_claim: string;
            /** @default email */
            username_claim: string;
            /** @description claim 值 → 角色；Keycloak 组路径会匹配末段 */
            role_map?: {
                [key: string]: string;
            };
            /** @default viewer */
            default_role: string;
            /** @default true */
            public_login: boolean;
            /** @default true */
            autocreate: boolean;
            /** @default true */
            sync_role: boolean;
            enabled?: boolean;
        };
        AuditExport: {
            id?: string;
            /** @enum {string} */
            format?: "csv" | "jsonl";
            /** @enum {string} */
            status?: "pending" | "done" | "failed";
            row_count?: number;
            error?: string;
            created_at?: string;
            completed_at?: string;
        };
        IdentityScope: {
            project_id?: string;
            project_slug?: string;
            /** @description 显式环境，禁止通配 */
            env?: string;
            /** @enum {string} */
            permission?: "read" | "reveal" | "write";
        };
        Identity: {
            id?: string;
            name?: string;
            client_id?: string;
            /** @enum {string} */
            status?: "active" | "revoked";
            token_ttl?: number;
            created_at?: string;
            scopes?: components["schemas"]["IdentityScope"][];
        };
        IdentityWithSecret: components["schemas"]["Identity"] & {
            /** @description 仅此一次展示 */
            client_secret?: string;
        };
        IdentityCreateRequest: {
            name: string;
            /** @default 900 */
            token_ttl: number;
            scopes: {
                project_id: string;
                env: string;
                /** @enum {string} */
                permission: "read" | "reveal" | "write";
            }[];
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
            name?: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        TokenPair: {
            access?: string;
            refresh?: string;
            /** @example Bearer */
            tokenType?: string;
            /** @example 900 */
            expiresIn?: number;
        };
        AuthResponse: {
            user?: components["schemas"]["User"];
            tokens?: components["schemas"]["TokenPair"];
        };
        DynamicEngine: {
            id?: string;
            name?: string;
            /** @example postgres */
            type?: string;
            database?: string;
            default_ttl?: number;
            max_ttl?: number;
            created_at?: string;
            leases?: components["schemas"]["DynamicLease"][];
        };
        DynamicEngineCreateRequest: {
            name: string;
            /** @enum {string} */
            type?: "postgres";
            /** @description 高权限连接串（postgres://…），加密落库 */
            connection_string: string;
            /** @default postgres */
            database: string;
            /** @default 3600 */
            default_ttl: number;
            /** @default 86400 */
            max_ttl: number;
        };
        DynamicLease: {
            id?: string;
            /** @example taboo_a1b2c3d4e5f6 */
            username?: string;
            /** @enum {string} */
            status?: "active" | "expired" | "revoked" | "failed";
            expires_at?: number;
            seconds_left?: number;
            created_at?: string;
        };
        LeaseCredentials: {
            id?: string;
            username?: string;
            /** @description 仅此一次明文返回 */
            password?: string;
            database?: string;
            expires_at?: number;
            seconds_left?: number;
        };
        LoginResponse: components["schemas"]["AuthResponse"] | {
            /** @constant */
            totp_required?: true;
            challenge?: string;
        };
    };
    responses: {
        /** @description 参数错误 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 未认证/凭证错误 */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 权限不足（RBAC），如 viewer 取明文、developer 写 prod */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 资源不存在 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 冲突（如邮箱已注册） */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 限流（5 次/分钟/IP，可用 TABOO_LOGIN_RATE_LIMIT 调整） */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        OrgSlug: string;
        Pid: string;
        Env: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 进程活着 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 就绪 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description DB 或 schema 异常 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listAuthSources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 登录选项 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        register_enabled?: boolean;
                        password_enabled?: boolean;
                        sources?: components["schemas"]["AuthSource"][];
                    };
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description 注册成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description 登录成功（或需二次验证） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    refresh: string;
                };
            };
        };
        responses: {
            /** @description 新 token 对 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    totpSetup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 待激活密钥（secret 明文仅此一次展示） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example JBSWY3DPEHPK3PXP */
                        secret?: string;
                        /** Format: uri */
                        otpauth_url?: string;
                        /** @description data:image/png;base64 */
                        qr_png?: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    totpVerify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example 123456 */
                    code: string;
                };
            };
        };
        responses: {
            /** @description 已开启 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        enabled?: boolean;
                        recovery_codes?: string[];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    totpDisable: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: password */
                    password: string;
                };
            };
        };
        responses: {
            /** @description 已关闭 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example false */
                        enabled?: boolean;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    totpLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description login 返回的 5min JWT */
                    challenge: string;
                    /** @description 6 位动态码或 xxxx-xxx-xxxx 恢复码 */
                    code: string;
                };
            };
        };
        responses: {
            /** @description 登录成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前用户 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user?: components["schemas"]["User"];
                        orgs?: components["schemas"]["OrgMembership"][];
                        totp_enabled?: boolean;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["OrgSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 项目列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        projects?: components["schemas"]["Project"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["OrgSlug"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                };
            };
        };
        responses: {
            /** @description 已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    audit: {
        parameters: {
            query?: {
                limit?: number;
                /** @description cursor 分页预留（当前按时间倒序 limit） */
                before?: string;
                action?: string;
                actor?: string;
                resource?: string;
                from?: string;
                to?: string;
            };
            header?: never;
            path: {
                slug: components["parameters"]["OrgSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 审计记录 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        logs?: components["schemas"]["AuditLog"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    verifyAudit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["OrgSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 验真结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok?: boolean;
                        checked?: number;
                        broken_at?: string;
                        checkpoint_ok?: boolean;
                    };
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    listMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["OrgSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成员 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        members?: components["schemas"]["OrgMember"][];
                    };
                };
            };
        };
    };
    addMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["OrgSlug"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    email: string;
                    /** @enum {string} */
                    role?: "owner" | "admin" | "developer" | "viewer";
                    restricted?: boolean;
                };
            };
        };
        responses: {
            /** @description 已添加 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    removeMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["OrgSlug"];
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已移除 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    patchMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["OrgSlug"];
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    role?: "owner" | "admin" | "developer" | "viewer";
                    restricted?: boolean;
                };
            };
        };
        responses: {
            /** @description 已更新 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    putMemberGrants: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["OrgSlug"];
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    grants?: {
                        project_id?: string;
                        role?: string;
                    }[];
                };
            };
        };
        responses: {
            /** @description 已更新 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["OrgSlug"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    email: string;
                    /** @enum {string} */
                    role?: "owner" | "admin" | "developer" | "viewer";
                };
            };
        };
        responses: {
            /** @description 邀请链接 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id?: string;
                        url?: string;
                        token?: string;
                        expires_at?: number;
                    };
                };
            };
        };
    };
    acceptInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已加入 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listIdentities: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["OrgSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 身份列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        identities?: components["schemas"]["Identity"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createIdentity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["OrgSlug"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IdentityCreateRequest"];
            };
        };
        responses: {
            /** @description 已创建（含一次性 client_secret） */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentityWithSecret"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    revokeIdentity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["OrgSlug"];
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已吊销 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    identityToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    client_id: string;
                    client_secret: string;
                };
            };
        };
        responses: {
            /** @description 短期 token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        access_token?: string;
                        /** @example Bearer */
                        token_type?: string;
                        /** @example 900 */
                        expires_in?: number;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
        };
    };
    listEnvs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: components["parameters"]["Pid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 环境列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        environments?: components["schemas"]["Environment"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createEnv: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: components["parameters"]["Pid"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                };
            };
        };
        responses: {
            /** @description 已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Environment"];
                };
            };
        };
    };
    listFolders: {
        parameters: {
            query?: {
                env?: components["parameters"]["Env"];
            };
            header?: never;
            path: {
                pid: components["parameters"]["Pid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 文件夹列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        folders?: components["schemas"]["Folder"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createFolder: {
        parameters: {
            query?: {
                env?: components["parameters"]["Env"];
            };
            header?: never;
            path: {
                pid: components["parameters"]["Pid"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example /db/mysql/ */
                    path: string;
                };
            };
        };
        responses: {
            /** @description 已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id?: string;
                        path?: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    deleteFolder: {
        parameters: {
            query: {
                env?: components["parameters"]["Env"];
                path: string;
            };
            header?: never;
            path: {
                pid: components["parameters"]["Pid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已删除 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    moveFolder: {
        parameters: {
            query?: {
                env?: components["parameters"]["Env"];
            };
            header?: never;
            path: {
                pid: components["parameters"]["Pid"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example /db/ */
                    from: string;
                    /** @example /database/ */
                    to: string;
                };
            };
        };
        responses: {
            /** @description 已移动 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    listSecrets: {
        parameters: {
            query?: {
                env?: components["parameters"]["Env"];
                path?: string;
            };
            header?: never;
            path: {
                pid: components["parameters"]["Pid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 密钥元数据列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        secrets?: components["schemas"]["SecretMeta"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    upsertSecret: {
        parameters: {
            query?: {
                env?: components["parameters"]["Env"];
                path?: string;
            };
            header?: {
                /** @description 幂等约定（v1.5 强制） */
                "Idempotency-Key"?: string;
            };
            path: {
                pid: components["parameters"]["Pid"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SecretUpsertRequest"];
            };
        };
        responses: {
            /** @description 已保存（含新版本号） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        version?: number;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
        };
    };
    revealSecret: {
        parameters: {
            query?: {
                env?: components["parameters"]["Env"];
                path?: string;
            };
            header?: never;
            path: {
                pid: components["parameters"]["Pid"];
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 明文 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecretValue"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    secretVersions: {
        parameters: {
            query?: {
                env?: components["parameters"]["Env"];
                path?: string;
            };
            header?: never;
            path: {
                pid: components["parameters"]["Pid"];
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 版本列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        versions?: components["schemas"]["SecretVersion"][];
                        latest?: number;
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    rollbackSecret: {
        parameters: {
            query?: {
                env?: components["parameters"]["Env"];
                path?: string;
            };
            header?: never;
            path: {
                pid: components["parameters"]["Pid"];
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    version: number;
                };
            };
        };
        responses: {
            /** @description 已回滚 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        version?: number;
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    exportSecrets: {
        parameters: {
            query?: {
                env?: components["parameters"]["Env"];
            };
            header?: never;
            path: {
                pid: components["parameters"]["Pid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description text/plain .env 内容 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": unknown;
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    listDynamicEngines: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: components["parameters"]["Pid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 引擎与活跃 lease */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        engines?: components["schemas"]["DynamicEngine"][];
                    };
                };
            };
        };
    };
    createDynamicEngine: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: components["parameters"]["Pid"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DynamicEngineCreateRequest"];
            };
        };
        responses: {
            /** @description 已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DynamicEngine"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
        };
    };
    requestLease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: components["parameters"]["Pid"];
                eid: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description 秒，默认引擎 default_ttl，上限 max_ttl */
                    ttl?: number;
                };
            };
        };
        responses: {
            /** @description lease 凭证（明文密码仅此一次返回） */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaseCredentials"];
                };
            };
            403: components["responses"]["Forbidden"];
            /** @description 目标库不可达/授权失败 */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    renewLease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: components["parameters"]["Pid"];
                lid: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    ttl?: number;
                };
            };
        };
        responses: {
            /** @description 已续期 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id?: string;
                        expires_at?: number;
                    };
                };
            };
            /** @description lease 非活跃 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    revokeLease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: components["parameters"]["Pid"];
                lid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已回收（或原本非活跃） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id?: string;
                        status?: string;
                    };
                };
            };
        };
    };
    listSyncTargets: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["OrgSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 目标列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        targets?: components["schemas"]["SyncTarget"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createSyncTarget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["OrgSlug"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncTargetInput"];
            };
        };
        responses: {
            /** @description 已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id?: string;
                        name?: string;
                        platform?: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
        };
    };
    deleteSyncTarget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["OrgSlug"];
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已删除 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id?: string;
                        deleted?: boolean;
                    };
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    retrySyncTarget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["OrgSlug"];
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已入队 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        target_id?: string;
                        enqueued?: number;
                    };
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listSyncRuns: {
        parameters: {
            query?: {
                target_id?: string;
                status?: "pending" | "success" | "failed" | "dead";
                limit?: number;
            };
            header?: never;
            path: {
                slug: components["parameters"]["OrgSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 同步记录 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        runs?: components["schemas"]["SyncRun"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listWebhooks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["OrgSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 订阅列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        webhooks?: components["schemas"]["Webhook"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["OrgSlug"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uri */
                    url: string;
                    /** @description HMAC 签名密钥（缺省自动生成） */
                    secret?: string;
                    /** @description 空 = 全部事件 */
                    events?: ("secret.created" | "secret.updated" | "secret.rolled_back" | "secret.deleted" | "*")[];
                };
            };
        };
        responses: {
            /** @description 已创建（secret 仅此一次返回） */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Webhook"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
        };
    };
    deleteWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["OrgSlug"];
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已删除 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id?: string;
                        deleted?: boolean;
                    };
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listWebhookDeliveries: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                slug: components["parameters"]["OrgSlug"];
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 投递记录 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        deliveries?: {
                            id?: string;
                            event?: string;
                            /** @enum {string} */
                            status?: "pending" | "success" | "failed" | "dead";
                            http_code?: number;
                            attempts?: number;
                            error?: string;
                            created_at?: string;
                            delivered_at?: string;
                        }[];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    oidcLogin: {
        parameters: {
            query?: {
                /** @description 指定 IdP 配置 id；缺省取该组织第一个已启用配置 */
                pid?: string;
            };
            header?: never;
            path: {
                slug: components["parameters"]["OrgSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 重定向到 IdP */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    oidcCallback: {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: never;
            path: {
                slug: components["parameters"]["OrgSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description HTML 中间页：token 写入 localStorage 后跳转 / */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description IdP 不可达/换 token 失败 */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listOIDCProviders: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["OrgSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 配置列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        providers?: components["schemas"]["OIDCProvider"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createOIDCProvider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["OrgSlug"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OIDCProviderInput"];
            };
        };
        responses: {
            /** @description 已接入 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id?: string;
                        name?: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
        };
    };
    deleteOIDCProvider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["OrgSlug"];
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已删除 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id?: string;
                        deleted?: boolean;
                    };
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateOIDCProvider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["OrgSlug"];
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OIDCProviderInput"];
            };
        };
        responses: {
            /** @description 已更新 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id?: string;
                        updated?: boolean;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    auditExport: {
        parameters: {
            query?: {
                format?: "csv" | "jsonl";
                action?: string;
                actor?: string;
                resource?: string;
                from?: string;
                to?: string;
                /** @description 强制异步：返回 202 + download_url */
                async?: "1";
            };
            header?: never;
            path: {
                slug: components["parameters"]["OrgSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 导出文件流（CSV/JSONL） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 异步任务已创建 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id?: string;
                        status?: string;
                        download_url?: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listAuditExports: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["OrgSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 任务列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        exports?: components["schemas"]["AuditExport"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    retryAuditExport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["OrgSlug"];
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已重新入队 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    downloadAuditExport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["OrgSlug"];
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 文件内容或任务状态 JSON */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
}
