{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "taboo.fullname" . }}
  labels:
    {{- include "taboo.labels" . | nindent 4 }}
spec:
  accessModes: [{{ .Values.persistence.accessMode }}]
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- with .Values.persistence.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
{{- end }}
